name: "[GAMA Plugin] Release with Maven"

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 21

    - name: Update Maven to 3.9.X
      run: |
        # Needed for Tycho 4.X.X and support for JDK 21
        wget https://dlcdn.apache.org/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz
        tar -xvf apache-maven-3.9.11-bin.tar.gz
        mv apache-maven-3.9.11 /opt/
        M2_HOME='/opt/apache-maven-3.9.11'
        PATH="$M2_HOME/bin:$PATH"
        export PATH
        # Overwrite PATH with updated maven install
        echo $PATH > $GITHUB_PATH
        echo "=== Check if well installed ==="
        echo "$ mvn -version"
        mvn -version

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'hqnghi88@gmail.com'

    - name: Build with Maven
      run: |
        mvn deploy -Prelease-composite -Dgithub-update-repo=https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/hqnghi88/llm_skill
      working-directory: "gama.experimental.llm.parent"
